#!/usr/bin/env python3
"""
build_board_doc.py

Render the optimal-trade board (data/trade_board.csv + data/trade_board_threeteam.csv, written by
trade_search.py) into the publication-facing markdown: the ranked two-team board, the honest
team-level no-deal verdicts, the targeted three-team section, and the Portfolio A/C benchmark line.
Cheap and re-runnable -- it does no simulation, it just formats the search's output.

    python build_board_doc.py
"""

import os
import csv

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
OUT = os.path.join(HERE, "..", "outputs")

# Portfolio A / C benchmark (championship_profiles.md): risk-adjusted dP range + 2027 flex.
PORT_A = ("Portfolio A (Randle->Smith + McBride + MLE + Dosunmu)", 1.75, "+1.7..+3.4", "HIGH")
PORT_C = ("Portfolio C (Randle->Smith + Mitchell + MLE + Dosunmu)", 1.62, "+1.6..+3.3", "HIGH")


def load(path):
    if not os.path.exists(path):
        return []
    return list(csv.DictReader(open(path, encoding="utf-8")))


def f(x, dflt=None):
    try:
        return float(x)
    except (ValueError, TypeError):
        return dflt


def sort_key(r):
    ra = f(r.get("risk_adj"))
    if ra is not None:
        return ra
    return f(r.get("dp_consensus"), -99)


# a deal only counts as "worthwhile" if it clears this risk-adjusted bar; below it, the best
# available deal does not move MIN's title needle and belongs with the no-fits (honest framing).
WORTHWHILE = 0.3


def main():
    rows = load(os.path.join(DATA, "trade_board.csv"))
    three = load(os.path.join(DATA, "trade_board_threeteam.csv"))
    raw_deals = [r for r in rows if r["verdict"] == "DEAL"]
    nodeals = [r for r in rows if r["verdict"] != "DEAL"]
    # demote net-negative / marginal "best deals" to the no-fit bucket
    deals = [r for r in raw_deals if sort_key(r) > WORTHWHILE]
    marginal = [r for r in raw_deals if sort_key(r) <= WORTHWHILE]
    deals.sort(key=sort_key, reverse=True)

    L = []
    L.append("# The optimal-trade board: every team, two-team then targeted three-team")
    L.append("\n_Companion to the portfolio capstone. For each of the 29 partners, the single best legal "
             "two-team trade that maximizes MIN's risk-adjusted championship dP on the aged spine SUBJECT "
             "TO the partner accepting it (acceptance defined from data: surplus-improvement, need-fill, or "
             "a data-gated cap-relief dump). Ranked by risk-adjusted dP; the 2027 war-chest state is carried "
             "as a co-equal axis (Pareto, never scalarized). Most teams return no worthwhile deal, and that "
             "is an honest finding, not a gap. Generated by trade_search.py; numbers are model output, not "
             "reporting._\n")
    L.append("> **Read the anchor, not the top.** Every surfaced deal carries a four-view range, and the "
             "conservative DARKO/box anchor on the best of them is near zero. These are coin-flip bets that "
             "cost real picks. On the dual axis (risk-adjusted title equity AND 2027 flexibility together), "
             "the recommended Portfolios A and C are not beaten by anything on this board.\n")
    L.append("> **Picks held.** The two incoming Utah firsts (2027/2029) are HELD OUT of every sweetener "
             "bill pending a per-deal Stepien + protection-window read; bills below spend only MIN's own, "
             "unconditioned chips (this year's pick, the 2028 and 2033 own firsts, seconds). No surfaced "
             "deal required a Utah first.\n")

    # ---- the benchmark line ----
    L.append("## Benchmark: the recommended portfolios\n")
    L.append("The board is measured against the two recommended no-blockbuster portfolios. A surfaced deal "
             "is only \"worthwhile\" if it beats or matches these on the risk-adjusted axis WITHOUT giving "
             "back the 2027 flexibility they preserve:\n")
    L.append("| Reference | Risk-adj dP | Four-view range | 2027 flex |")
    L.append("|---|---|---|---|")
    for name, ra, rng, flex in (PORT_A, PORT_C):
        L.append(f"| {name} | **{ra:+.2f}** | {rng} | {flex} |")

    # ---- the ranked two-team board ----
    L.append("\n## The ranked two-team board\n")
    L.append("| # | Partner | MIN sends | MIN gets | Asset bill (own picks only) | Accept | "
             "Views cons/box/rapm/DARKO | Anchor | Risk-adj dP | 2027 flex | Sourcing |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for i, r in enumerate(deals, 1):
        views = f"{r.get('dp_consensus','')}/{r.get('dp_box','')}/{r.get('dp_rapm','')}/{r.get('dp_darko','') or 'n/a'}"
        ra = r.get("risk_adj", "")
        ra_s = f"**{f(ra):+.2f}**" if f(ra) is not None else "(screen only)"
        src = "Speculative" if str(r.get("sourcing", "")).startswith("Spec") else "model"
        L.append(f"| {i} | **{r['partner']}** | {r['min_sends']} | {r['min_gets']} | {r['sweetener']} | "
                 f"{r['accept_channel']} ({r['partner_posture']}) | {views} | {r.get('anchor','')} | {ra_s} | "
                 f"{r['flex_2027']} | {src} |")

    # ---- vs the benchmark ----
    beats = [r for r in deals if f(r.get("risk_adj"), -99) >= PORT_C[1] and r["flex_2027"] == "HIGH"]
    L.append(f"\n**Versus the portfolios:** {len(beats)} surfaced deal(s) match or beat Portfolio C's "
             f"{PORT_C[1]:+.2f} risk-adjusted while preserving HIGH 2027 flexibility "
             f"({', '.join(r['partner'] for r in beats) or 'none'}). "
             "Deals that beat the portfolios on dP but carry LOW/MODERATE flex are Pareto trade-offs: more "
             "title equity now for a clogged 2027, the same tension Portfolio B carries.")

    # ---- no-deal verdicts ----
    L.append("\n## The honest no-deal majority\n")
    L.append("These partners return no realistic two-team deal that improves both sides. The reason is the "
             "adverse-selection screen working as designed: contenders will not sell, cornerstones are not "
             "available, and a team with nothing MIN wants (or no way to absorb MIN's salary) is a no-deal, "
             "not a failure.\n")
    L.append("| Partner | Posture | Why no worthwhile deal |")
    L.append("|---|---|---|")
    for r in sorted(nodeals, key=lambda r: r["partner"]):
        why = r["min_gets"].replace("(near: ", "").rstrip(")")
        L.append(f"| {r['partner']} | {r['partner_posture']} | {why} |")
    for r in sorted(marginal, key=sort_key):
        ra = f(r.get("risk_adj"))
        ra_s = f"risk-adj {ra:+.2f}" if ra is not None else f"dP {r.get('dp_consensus','')}"
        L.append(f"| {r['partner']} | {r['partner_posture']} | best legal+accepted deal "
                 f"({r['min_gets']}) is net-negligible for MIN ({ra_s}) -- not worth the assets |")

    # ---- three-team ----
    L.append("\n## Targeted three-team deals (Pass 2)\n")
    if three:
        L.append("Surfaced ONLY where a third team is structurally necessary -- the two-team version is "
                 "illegal or rejected, and the third team resolves that specific blockage. Each reports why.\n")
        L.append("| MIN gets | Partner | Third team | Routed | dP | Why the third team is needed |")
        L.append("|---|---|---|---|---|---|")
        for r in three:
            L.append(f"| {r['min_gets']} | {r['partner']} | {r['third_team']} | {r['routed']} | "
                     f"{r['dp_consensus']} | {r['why']} |")
    else:
        L.append("_No Pass-1 near-miss resolved into a legal, accepted three-team deal. The salary-blocked "
                 "near-misses (contenders who could not absorb MIN's outbound) did not produce a third-team "
                 "route where all three sides clear acceptance and feasibility._")

    # ---- caveats ----
    L.append("\n## Caveats carried into the writeup\n")
    L.append("- **Acceptance is a model of willingness, not reporting.** Deals involving a $38M+ star "
             "(AD, Kyrie, Morant, Trae) are CONDITIONAL on that team choosing to pivot; they are surfaced "
             "because the posture math allows it, not because the player is reported available.")
    L.append("- **The acceptance model is Minnesota-acquisition-scoped with hand-set coefficients.** Its "
             "Phase 2-C knobs are not calibrated against realized trades (a realized-trade backtest proved "
             "it does not generalize to arbitrary trades; see `docs/acceptance_model_scope_and_limitation.md`). "
             "Trust the strong deals over the exact MARGINAL ranking.")
    L.append("- **Salary matching is exact-number sensitive.** Any surfaced player's precise 2026-27 cap "
             "hit (and `salary_is_estimate` contracts) needs a Spotrac verify before a deal is called real.")
    L.append("- **The conservative anchor is the lowest available view** (usually DARKO, which is bearish "
             "on role players); headline the anchor and risk-adjusted EV, never the consensus/RAPM top.")
    L.append("- **Incumbent-default lineups:** the acquired player inherits the traded player's role, which "
             "can pair two centers; a real deal would re-optimize the rotation.")
    L.append("- **Re-routed UTA incoming firsts** carry protection/Stepien conditions read per deal.")

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "optimal_trade_board.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote outputs/optimal_trade_board.md  ({len(deals)} worthwhile deals, "
          f"{len(nodeals)+len(marginal)} no-fit ({len(nodeals)} no-deal + {len(marginal)} marginal), "
          f"{len(three)} three-team)")


if __name__ == "__main__":
    main()
